// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fkfxaddswlkjbqzyqgdx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZrZnhhZGRzd2xramJxenlxZ2R4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU0NDg0OTMsImV4cCI6MjA5MTAyNDQ5M30.d7_6xU0xbyCuBDD5qCpRbiA5djby8UG159OIKLwQg6Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});